SERVER.classes	+= gameMaster.impl.ServerGameMasterImpl \
		   gameMaster.impl.ServerGameImpl \
		   gameMaster.impl.ServerPlayerControlImpl \
		   gameMaster.impl.ProxyGame$$LocalListener \
		   gameMaster.impl.ServerGameImpl$$GameLandlord
